version: "3.7"

services:
  postgres-svc:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - esimed-backend-data:/var/lib/postgresql/data

  adminer-svc:
    image: adminer
    ports:
      - 8080:8080

volumes:
  esimed-backend-data: